import { StatusBar } from "expo-status-bar";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

type Form = { pregnancies: number; glucose: number; blood_pressure: number; skin_thickness: number; insulin: number; bmi: number; diabetes_pedigree_function: number; age: number };
const initial: Form = { pregnancies: 1, glucose: 120, blood_pressure: 70, skin_thickness: 20, insulin: 80, bmi: 30, diabetes_pedigree_function: 0.4, age: 30 };
const fields: [keyof Form, string][] = [["pregnancies", "Số lần mang thai"], ["glucose", "Glucose"], ["blood_pressure", "Huyết áp"], ["skin_thickness", "Độ dày da"], ["insulin", "Insulin"], ["bmi", "BMI"], ["diabetes_pedigree_function", "Chỉ số di truyền"], ["age", "Tuổi"]];
const API_URL = "http://10.0.2.2:8001/predict/diabetes";

export default function App() {
  const [form, setForm] = useState(initial); const [result, setResult] = useState<any>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function predict() { setLoading(true); setError(""); try { const response = await fetch(API_URL, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) throw Error(); setResult(await response.json()); } catch { setError("Không thể kết nối API. Hãy khởi động FastAPI trên cổng 8001."); } finally { setLoading(false); } }
  const score = result ? Math.round(result.disease_probability * 100) : 0;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><StatusBar style="dark" /><Header subtitle="DIABETES PREDICTION / 01" /><View style={styles.intro}><Text style={styles.eyebrowMint}>DIABETES DASHBOARD</Text><Text style={styles.title}>Dự đoán bệnh tiểu đường</Text><Text style={styles.description}>Nhập các chỉ số y tế để ước tính nguy cơ mắc bệnh.</Text></View><View style={styles.panel}><Title index="01 / DỮ LIỆU ĐẦU VÀO" text="Thông tin bệnh nhân" />{fields.map(([key, label]) => <View style={styles.field} key={key}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} keyboardType="decimal-pad" value={String(form[key])} onChangeText={(value) => setForm({ ...form, [key]: Number(value) || 0 })} /></View>)}<Pressable style={styles.button} onPress={predict} disabled={loading}><Text style={styles.buttonText}>{loading ? "Đang phân tích..." : "◎  Dự đoán  ↗"}</Text></Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}</View><View style={styles.panel}><Title index="02 / KẾT QUẢ MÔ HÌNH" text="Nguy cơ tiểu đường" /><Text style={styles.score}>{score}<Text style={styles.percent}>%</Text></Text><Metric label="XÁC ĐỊNH" value={result ? (result.prediction ? "Có nguy cơ" : "Nguy cơ thấp") : "Chưa có dữ liệu"} /><Metric label="MỨC ĐỘ RỦI RO" value={result?.risk_level ?? "Chưa có dữ liệu"} /><Metric label="MÔ HÌNH" value="Logistic Regression" /><View style={styles.track}><View style={[styles.fill, { width: `${score}%` }]} /></View><Text style={styles.note}>Kết quả hỗ trợ sàng lọc, không thay thế chẩn đoán y khoa.</Text></View></ScrollView>;
}
function Header({ subtitle }: { subtitle: string }) { return <View style={styles.header}><View style={styles.brandRow}><View style={styles.logo}><Text style={styles.logoText}>⌁</Text></View><View><Text style={styles.brand}>PULSEBOARD</Text><Text style={styles.eyebrow}>{subtitle}</Text></View></View><Text style={styles.online}>● ĐANG HOẠT ĐỘNG</Text></View>; }
function Title({ index, text }: { index: string; text: string }) { return <View style={styles.titleBlock}><Text style={styles.eyebrow}>{index}</Text><Text style={styles.heading}>{text}</Text></View>; }
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#f4f7f6" }, content: { padding: 18, paddingBottom: 30 }, header: { borderBottomWidth: 1, borderBottomColor: "#dce5e2", paddingBottom: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, brandRow: { flexDirection: "row", alignItems: "center", gap: 10 }, logo: { width: 34, height: 34, borderRadius: 7, backgroundColor: "#8ce3c3", alignItems: "center", justifyContent: "center" }, logoText: { fontSize: 23, color: "#17201e", fontWeight: "700" }, brand: { color: "#1f2c29", fontSize: 14, fontWeight: "700" }, online: { color: "#329d79", fontSize: 8, fontWeight: "700", maxWidth: 110, textAlign: "right" }, eyebrow: { color: "#71807c", fontSize: 8, fontWeight: "700", letterSpacing: 1.1 }, eyebrowMint: { color: "#328b70", fontSize: 9, fontWeight: "700", letterSpacing: 1.1 }, intro: { paddingVertical: 26 }, title: { color: "#1f2c29", fontSize: 28, fontWeight: "700", marginTop: 8 }, description: { color: "#64716f", fontSize: 12, lineHeight: 19, marginTop: 8 }, panel: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#dce5e2", borderRadius: 8, padding: 18, marginBottom: 16, shadowColor: "#243b35", shadowOpacity: .06, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 1 }, titleBlock: { marginBottom: 18 }, heading: { color: "#1f2c29", fontSize: 19, fontWeight: "700", marginTop: 6 }, field: { marginBottom: 13 }, label: { color: "#42524e", fontSize: 12, marginBottom: 6 }, input: { height: 43, borderWidth: 1, borderColor: "#cbd8d4", borderRadius: 6, paddingHorizontal: 12, color: "#1f2c29", fontSize: 13, fontWeight: "600", backgroundColor: "#fbfdfc" }, button: { backgroundColor: "#70c9aa", borderRadius: 6, paddingVertical: 13, alignItems: "center", marginTop: 3 }, buttonText: { color: "#17201e", fontWeight: "700", fontSize: 12 }, error: { color: "#a33d35", backgroundColor: "#fff0ee", padding: 10, borderRadius: 5, fontSize: 11, marginTop: 14 }, score: { color: "#70c9aa", fontSize: 76, lineHeight: 80, fontWeight: "600", marginVertical: 20 }, percent: { fontSize: 23 }, metric: { borderWidth: 1, borderColor: "#dce5e2", borderRadius: 5, backgroundColor: "#f7faf9", padding: 12, marginBottom: 8 }, metricLabel: { color: "#71807c", fontSize: 8, fontWeight: "700" }, metricValue: { color: "#1f2c29", fontSize: 12, fontWeight: "600", marginTop: 5 }, track: { height: 5, backgroundColor: "#dce5e2", borderRadius: 4, overflow: "hidden", marginTop: 10 }, fill: { height: 5, backgroundColor: "#51b892" }, note: { color: "#71807c", fontSize: 10, lineHeight: 16, marginTop: 12 } });
