import { StatusBar } from "expo-status-bar";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

type Form = { address: string; area: number; frontage: number; access_road: number; floors: number; bedrooms: number; bathrooms: number; legal_status: string; furniture_state: string };
const initial: Form = { address: "Phường 11, Gò Vấp, Hồ Chí Minh", area: 80, frontage: 5, access_road: 4, floors: 3, bedrooms: 3, bathrooms: 2, legal_status: "Have certificate", furniture_state: "Full" };
const fields: [keyof Form, string][] = [["area", "Diện tích (m²)"], ["frontage", "Mặt tiền (m)"], ["access_road", "Đường vào (m)"], ["floors", "Số tầng"], ["bedrooms", "Phòng ngủ"], ["bathrooms", "Phòng tắm"]];
const API_URL = "http://10.0.2.2:8002/predict/house-price";

export default function App() {
  const [form, setForm] = useState(initial); const [result, setResult] = useState<any>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function predict() { setLoading(true); setError(""); try { const response = await fetch(API_URL, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) throw Error(); setResult(await response.json()); } catch { setError("Không thể kết nối API. Hãy khởi động FastAPI trên cổng 8002."); } finally { setLoading(false); } }
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><StatusBar style="dark" /><Header /><View style={styles.intro}><Text style={styles.eyebrowMint}>HOUSE PRICE DASHBOARD</Text><Text style={styles.title}>Dự đoán giá nhà đất 2024</Text><Text style={styles.description}>Nhập thông tin bất động sản để ước tính giá trị thị trường.</Text></View><View style={styles.panel}><Title index="01 / DỮ LIỆU ĐẦU VÀO" text="Thông tin bất động sản" /><View style={styles.field}><Text style={styles.label}>Địa chỉ</Text><TextInput style={styles.input} value={form.address} onChangeText={(value) => setForm({ ...form, address: value })} /></View>{fields.map(([key, label]) => <View style={styles.field} key={key}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} keyboardType="decimal-pad" value={String(form[key])} onChangeText={(value) => setForm({ ...form, [key]: Number(value) || 0 })} /></View>)}<Pressable style={styles.button} onPress={predict} disabled={loading}><Text style={styles.buttonText}>{loading ? "Đang phân tích..." : "◎  Dự đoán  ↗"}</Text></Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}</View><View style={styles.panel}><Title index="02 / KẾT QUẢ MÔ HÌNH" text="Giá nhà dự kiến" /><Text style={styles.score}>{result?.predicted_price ?? 0}<Text style={styles.unit}> tỷ</Text></Text><Metric label="ĐƠN VỊ" value={result?.unit ?? "tỷ VNĐ"} /><Metric label="MÔ HÌNH" value="Random Forest Regressor" /><Metric label="NĂM THAM CHIẾU" value="2024" /><Text style={styles.note}>Giá tham khảo dựa trên các đặc trưng bất động sản đã nhập.</Text></View></ScrollView>;
}
function Header() { return <View style={styles.header}><View style={styles.brandRow}><View style={styles.logo}><Text style={styles.logoText}>⌁</Text></View><View><Text style={styles.brand}>PULSEBOARD</Text><Text style={styles.eyebrow}>HOUSE PRICE / 02</Text></View></View><Text style={styles.online}>● ĐANG HOẠT ĐỘNG</Text></View>; }
function Title({ index, text }: { index: string; text: string }) { return <View style={styles.titleBlock}><Text style={styles.eyebrow}>{index}</Text><Text style={styles.heading}>{text}</Text></View>; }
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#f4f7f6" }, content: { padding: 18, paddingBottom: 30 }, header: { borderBottomWidth: 1, borderBottomColor: "#dce5e2", paddingBottom: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, brandRow: { flexDirection: "row", alignItems: "center", gap: 10 }, logo: { width: 34, height: 34, borderRadius: 7, backgroundColor: "#8ce3c3", alignItems: "center", justifyContent: "center" }, logoText: { fontSize: 23, color: "#17201e", fontWeight: "700" }, brand: { color: "#1f2c29", fontSize: 14, fontWeight: "700" }, online: { color: "#329d79", fontSize: 8, fontWeight: "700", maxWidth: 110, textAlign: "right" }, eyebrow: { color: "#71807c", fontSize: 8, fontWeight: "700", letterSpacing: 1.1 }, eyebrowMint: { color: "#328b70", fontSize: 9, fontWeight: "700", letterSpacing: 1.1 }, intro: { paddingVertical: 26 }, title: { color: "#1f2c29", fontSize: 28, fontWeight: "700", marginTop: 8 }, description: { color: "#64716f", fontSize: 12, lineHeight: 19, marginTop: 8 }, panel: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#dce5e2", borderRadius: 8, padding: 18, marginBottom: 16, shadowColor: "#243b35", shadowOpacity: .06, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: 1 }, titleBlock: { marginBottom: 18 }, heading: { color: "#1f2c29", fontSize: 19, fontWeight: "700", marginTop: 6 }, field: { marginBottom: 13 }, label: { color: "#42524e", fontSize: 12, marginBottom: 6 }, input: { height: 43, borderWidth: 1, borderColor: "#cbd8d4", borderRadius: 6, paddingHorizontal: 12, color: "#1f2c29", fontSize: 13, fontWeight: "600", backgroundColor: "#fbfdfc" }, button: { backgroundColor: "#70c9aa", borderRadius: 6, paddingVertical: 13, alignItems: "center", marginTop: 3 }, buttonText: { color: "#17201e", fontWeight: "700", fontSize: 12 }, error: { color: "#a33d35", backgroundColor: "#fff0ee", padding: 10, borderRadius: 5, fontSize: 11, marginTop: 14 }, score: { color: "#70c9aa", fontSize: 58, lineHeight: 64, fontWeight: "600", marginVertical: 20 }, unit: { fontSize: 20 }, metric: { borderWidth: 1, borderColor: "#dce5e2", borderRadius: 5, backgroundColor: "#f7faf9", padding: 12, marginBottom: 8 }, metricLabel: { color: "#71807c", fontSize: 8, fontWeight: "700" }, metricValue: { color: "#1f2c29", fontSize: 12, fontWeight: "600", marginTop: 5 }, note: { color: "#71807c", fontSize: 10, lineHeight: 16, marginTop: 8 } });
